name: CI Pipeline

on:
  push:
    branches: [ main, develop, feature/**, fix/** ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    
    - name: Run checkstyle (informational only)
      continue-on-error: true
      run: mvn checkstyle:check
    
    - name: Run OWASP dependency check
      run: mvn org.owasp:dependency-check-maven:check -DskipSystemScope=true -DskipProvidedScope=true -DskipTestScope=true
    
    - name: Build with Maven
      run: mvn -B package -DskipTests
    
    - name: Run Unit Tests with Coverage
      run: mvn test jacoco:report -Dspring.profiles.active=test
      
    - name: Run BDD Tests
      run: mvn test -Dtest=CucumberIntegrationTest -Dspring.profiles.active=test
    
    - name: Generate Javadoc
      run: mvn javadoc:javadoc
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: jar-and-docs
        path: |
          target/*.jar
          target/site/apidocs
